services:
  postgres:
    image: postgres:16-alpine
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_dob_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  backend:
    build: .
    container_name: go_backend_api
    restart: always
    depends_on:
      - postgres
    environment:
      - ENV=docker
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  pgdata: